<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PermutationOptimiser</RootNamespace>
    <AssemblyName>PermutationOptimiser</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PermutationOptimiser.Tests/**" />
    <EmbeddedResource Remove="PermutationOptimiser.Tests/**" />
    <None Remove="PermutationOptimiser.Tests/**" />
  </ItemGroup>

</Project>
